Setup find_installed_packages to fix bootstrap instructions
colcon/colcon-core pull request #472
Opened 2022-01-21 21:51 UTC by sloretz

Fix an issue from #449 - the bootstrap from source instructions are failing with the following error

```
[0.267s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': get_entry_points() not overridden for group 'colcon_core.shell.find_installed_packages'
Traceback (most recent call last):
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 298, in get_command_environment
    return await extension.generate_command_environment(
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/sh.py", line 137, in generate_command_environment
    check_dependency_availability(
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 510, in check_dependency_availability
    packages_in_env = find_installed_packages_in_environment()
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 552, in find_installed_packages_in_environment
    pkgs = find_installed_packages(prefix_path)
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 621, in find_installed_packages
    prioritized_extensions = get_find_installed_packages_extensions()
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 601, in get_find_installed_packages_extensions
    extensions = instantiate_extensions(__name__ + '.find_installed_packages')
  File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/plugin_system.py", line 36, in instantiate_extensions
    extension_types = load_entry_points(
  File "./src/colcon-core/bin/colcon", line 28, in custom_load_entry_points
    assert group_name in custom_entry_points, \
AssertionError: get_entry_points() not overridden for group 'colcon_core.shell.find_installed_packages'
```

I thought CI covered the bootstrap case, so I'm not sure why this wasn't caught.

2022-01-21 23:47 UTC, cottsay approved these changes

2022-01-21 23:49 UTC, cottsay requested changes
Actually, can you make the addition to the dict alphabetical?

2022-01-22 00:02 UTC, sloretz commented
@cottsay Oops, alphabetical order in c701499

2022-01-22 02:00 UTC, cottsay approved these changes

2022-01-22 02:01 UTC, merged