Capture stdout and stderr
colcon/colcon-core pull request #496
Opened 2022-03-23 15:57 UTC by esteve

This PR adds the output of running a process to the `stdout` and `stderr` fields of the returned [subprocess.CompletedProcess](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess).

The rationale for this change is that because when running some build tools (e.g. Rust's `cargo`), they don't save their output to a file, so it's not possible to expose their results to `colcon` (e.g. saving test results for `colcon test-result`)

2022-03-23 19:43 UTC, mikepurvis commented
I definitely thought this already happened. Are the logs in the `log` folder coming directly from the upstream tools vs being piped through colcon-core?

2022-03-24 11:07 UTC, esteve commented
@mikepurvis I believe the flow is that all output is redirected to `colcon`'s internal event queue which is then passed to the executor, which in turn dumps it into the `log` directory. However, nowhere in between you can access the process output unless you rewrite the `run` function from `colcon_core.subprocess` (see for example `check_call_return_stdout` in https://github.com/colcon/colcon-cargo/pull/4 as a workaround).

2022-03-31 17:47 UTC, cottsay requested changes
I really don't like buffering all of the console output as a default behavior. This needs to be made conditional somehow, and the default behavior should not change.

Some ideas:
1. `subprocess.run` uses a `capture_output` argument to control this.
2. we could introduce special marker callbacks to pass to `std{out,err}_callback`, something like `colcon_core.subprocess.CAPTURE` or something. This has the added advantage of being inherently mutually exclusive with an explicit callback.
3. introduce a wrapper function to `run` that passes the wrapper callbacks to `run` and adds the captured output on the way out.

Don't get me wrong - I'm totally on board with supporting output capture somehow. I can already think of a handful of spots that will take advantage of it.

2022-04-26 09:48 UTC, esteve commented
@cottsay thanks for the feedback. Of the three options, I think the first one seems the simplest and most straightfoward, and IMHO the cleanest from a user's perspective, I'm going to implement that shortly and push it.

2022-04-26 09:54 UTC, esteve commented
@cottsay I've just pushed the changes implementing option 1 in 1218230e891e5d510ee58cf1ad50d97c58e5307d

2022-05-03 17:09 UTC, cottsay approved these changes
Thanks for iterating. This looks like a great solution.

2022-05-03 17:21 UTC, merged

2022-05-16 13:50 UTC, esteve commented
@cottsay thanks for the feedback and merging this PR :slightly_smiling_face: